### ISSUE TITLE
Add comments to projects

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#10]
>Must be able to add a comment that is specific to a transportation project depicted on the map

>All transportation projects will be stored in the same feature class and may be geographically co-located with, or with portions of, other projects 

>May need to be able to comment on land use areas. Issue: separate dataset (polygon) to which comments would need to be directly related

>Should employ a primary/foreign key relationship between the feature class (projects/areas) and comments table.
May use a geodatabase relationship class 
Relationship between projects or land areas to comments is ‘0 to many’
Data should be stored on WFRC GIS server or ArcGIS Online

This may need to be implemented as an option in the ProjectInfo widget rather than a completely separate widget.

**Comment by stdavis** [comment]
@msilski: What about the "likes" feature in the public comment template? Do you want that implemented in this widget?

**Comment by stdavis** [comment]
@msilski: What fields do you want marked as required for submitting a comment?

**Comment by msilski** [comment]
The visible fields for commenting are just the ones you have in the widget - Name, Organization, Contact Information (e-mail/phone), and Comment. Comment is the only field that should be required.
