### ISSUE TITLE
Comments Moderation

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#12]
>Ability to review/disable comments (without information loss), can be manual

@msilski: How do you see this functionality working? Should we just add a boolean field to the comments table called "DISABLED" and allow you to manually change this value on the back end? How does the community feedback template handle this?

**Comment by msilski** [comment]
In the community feedback template, the ability to enable/disable commenting is a property in a config file (specifically "commentPeriod": "Closed" or "Open" in the config/defaults.js file). We would like to have the same functionality.

I noticed in the config file for the ProjectInfo widget that you included a "commentsEnabled" property - that would work for us.
