### ISSUE TITLE
Display Existing Comments

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#13]
>List of comments made should be expandable (full detail)/collapsible (summary)

**Comment by stdavis** [comment]
@msilski: I'd like more details on the expand/collapse feature for existing comments. What should it look like when it's collapsed?

**Comment by msilski** [comment]
When the list of public comments is collapsed, Bert and I liked the idea of text similar to how you have it but with the number of comments next to it, such as this:

Public Comments (0)

When expanded, it would show public comments in an indented list in smaller font. It would only display the timestamp and comment text (ideally, sorted newest on top).

**Comment by msilski** [comment]
@stdavis I was testing the new release of ProjectInfo and found that the number of comments do not increment once a comment is submitted. See before and after submitting the fourth comment:

![existing comments before](https://user-images.githubusercontent.com/1699870/45977301-67e1fb00-c006-11e8-8304-0d479a17c740.JPG)

![existing comments after](https://user-images.githubusercontent.com/1699870/45977467-f9ea0380-c006-11e8-95a2-7d1de425aec3.JPG)

They do increment when the page is refreshed. Would it be possible to have that number updated when the comment is submitted to the database?

**Comment by stdavis** [comment]
Nice catch! I'll fix it now and push a new release.

**Comment by stdavis** [comment]
I just pushed v0.3.1 with the bug fix for this issue.
