### ISSUE TITLE
New Icon for ProjectInfo Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#14]
@msilski: Do you have any preferences for the icon? I noticed that you changed it to 
![image](https://user-images.githubusercontent.com/1326248/45896316-fcdbbe80-bd90-11e8-9e0a-bb69b7160a81.png) in your app.

**Comment by msilski** [comment]
Good question. I just copied over the icon from the About widget. I will bring it back to the group and we'll settle on something. Creating a new icon is something our graphic designer or I can do.

**Comment by msilski** [comment]
We will bring this up with the internal group tomorrow morning.

**Comment by msilski** [comment]
Our group likes the current icon. If there is a future release of the ProjectInfo widget, do you mind including it in the release? It is in the widgets directory here: _root_\widgets\About\images\icon.png

**Comment by stdavis** [comment]
Done. Let me know if you want me to use different icons on any of the other widgets.
