### ISSUE TITLE
Expandable Images in About Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#15]
@msilski: Does this look like what you are looking for for images in the about widget?

![screencast](http://g.recordit.co/TnCbEG7AU0.gif)

**Comment by msilski** [comment]
Yes, this looks great. How difficult would it be to add an X in the top right corner of the expanded image for the user to collapse it? The average user should know to click outside the image to close it, but there may be users who look for the X in the top right corner to close/collapse it.

**Comment by stdavis** [comment]
I think that I can do that...
