### ISSUE TITLE
Legend Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#16]
>Ability to show grouping by phase (1, 2, 3, unfunded)
>Ability to show grouping by mode (roadway, transit, bike/ped)
>Each layer in a legend graphic shows both the layer name and symbol in a space efficient manner (could be static images)

@msilski: A few questions:
1. Is the symbology for the projects in this map: http://wfrc.org/rtp-2019-phasing/ the method that you will be using? That is, will you be symbolizing phases with color and mode by symbol?
1. Do you want all projects showing by default?
1. After thinking more about this widget...it's more than just a legend, right? You want to be able to filter by phase or type, correct?

Some use cases would be helpful with this widget. Here's an example:

>I'd like to be able to view only phase one projects symbolized by mode.
>I'd like to be able to view only phase one and two projects.
>I'd like to see a legend that shows me ...

I'd be happy to do a call on this if it's easier.

**Comment by nathankota** [comment]
The legend and 'filtering' by phase/mode do seem to be two different items. The legend is described in slide 3 of the mockup, while the filter is driven by the "View Projects By" pull-down selections in the upper, right corner of the mockup.

**Comment by stdavis** [comment]
WFRC has decided to stick with the out-of-the-box widget for now.
