### ISSUE TITLE
URL Parameters Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#17]
>Ability to add parameters to URL
>Possible types of parameters:
>* Extent (ex. &place=murray or &place=potm)
>* Mode (ex. &mode=transit or &mode=bike)
>* Phase (ex. &phase=1 or &phase=unfunded)
>* View states (ex. &infopanel = open or &infopanel = closed)
>* Other possibilities to be considered or as future options:
	* ClickXY (would open to a centered extent and open results window for that location
	* ProjectID (would open to a selected extent and open results window for that single project)

>Bookmarks widget in Web AppBuilder with WFRC provided list of named areas (see extent URL parameter) and their map extents

@msilski: Is this widget intended to be used along side the out-of-the-box bookmarks widget?

**Comment by stdavis** [comment]
- [x] extent (via x, y, and scale)
- [ ] place name (waiting on where I should get the data for this)
- [ ] phase
- [ ] mode
- [ ] infopanel open/closed (not sure if this will be possible)
- [ ] click x/y
- [ ] project id

**Comment by msilski** [comment]
I finally tested this widget. It works great. I see that the scale numbers correspond with the standard ArcGIS Online ones. I will check with @bertgranberg to see what he thinks before I deploy it to the live RTP phasing map.

**Comment by bertgranberg** [comment]
My prioritization order: (descending)

extent/scale
phase and mode filters
projectid (would assume a project had been clicked on and display info for that project)
info panel open/closed
click x/y (if i remember right this would bring the map to a state where a map click event had already happened)
basemap selection
other layer visibility
placename

**Comment by stdavis** [comment]
I updated my comment above with the new priorities as well as items we are waiting on.
