### ISSUE TITLE
Spanish Versions

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#18]
Add a config option for each widget that switches between English and Spanish rather than relying on the locale of the browser. WFRC creates two separate applications for the two languages.

**Comment by stdavis** [comment]
ProjectInfo is currently the only widget that this applies to. BetterAbout and URLParams don't have any UI text that is visible to the user.

**Comment by stdavis** [comment]
@msilski: Here are the strings that need to be translated:
"instructions": "Click on a project on the map to view information and leave comments.",
"leaveComment": "Leave comment",
"name": "Name",
"organization": "Organization",
"contact": "Contact Information (email/phone)",
"comment": "Comment*",
"submit": "Submit",
"cancel": "Cancel",
"required": "*Required",
"publicComments": "Public Comments",
"show": "Show",
"hide": "Hide"

These can be set in the config object for the ProjectInfo widget. If you want to send me the translations, I can add them to the default config for the widget.

**Comment by msilski** [comment]
I forgot about this one. Here are the Spanish strings:

"instructions": "Haga click sobre un proyecto en el mapa para ver la información y comentar.",
"leaveComment": "Comentar",
"name": "Nombre",
"organization": "Organización",
"contact": "Contacto (teléfono/correo electrónico)",
"comment": "Comentario*",
"submit": "Enviar",
"cancel": "Cancelar",
"required": "*Solicitado",
"publicComments": "Comentarios del Público",
"show": "Mostrar",
"hide": "Esconder"

**Comment by stdavis** [comment]
I'll include these in the default config for the ProjectInfo widget in the next release. It's probably easier for you to just manually change these value in the config for this widget within your application.
