### ISSUE TITLE
Auto-expand on map click if panel is closed

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#23]

**Comment by msilski** [comment]
A few weeks ago, I made an attempt to complete this. It is not the most elegant execution, but now the widget opens on map click even if the panel is closed or another in-panel widget is open. You are welcome to clean them up or leave them as-is. Attached are the modified files.

~/widgets/ProjectInfo/ProjectInfo/ProjectInfo.js
[ProjectInfo.zip](https://github.com/agrc/wfrc-wab-widgets/files/2621435/ProjectInfo.zip)

~/jimu.js/PanelManager.js
[PanelManager.zip](https://github.com/agrc/wfrc-wab-widgets/files/2621440/PanelManager.zip)

**Comment by stdavis** [comment]
I love that you're not afraid to get your hands dirty! I took your code and simplified it a bit. You can check it out here: https://github.com/agrc/wfrc-wab-widgets/commit/01b7538122198ffa56e352c013d474690347497d

I was also able to do it without editing `~/jimu.js/PanelManager.js`. I would highly recommend staying away from editing files outside of the widgets and config files. Otherwise, when Esri updates WAB in the future, your changes may be overwritten.

Also, in the future, if you'd like to contribute code, it would be better if you submit a pull request directly to this repository. For this project, it is especially important because the source code is transpiled via [babel](https://babeljs.io/) before I zip it up for production. So it makes it hard to determine what changes you've made if you edit the production code directly.

**Comment by msilski** [comment]
Thanks for the feedback, and for cleaning up that code. I will replace what I have with what you cleaned up in the next release.
