### ISSUE TITLE
ProjectInfo Widget in IE

### ISSUE THREAD

**Issue by msilski** [agrc/wfrc-wab-widgets#24]
We have had some users open the RTP phasing map in IE and found that when a user clicks on a project, the Project Information widget does not show projects in the project list. I don't think it is related to the changes I made a month ago to keep the widget on and open, as I tested an older version of the widget and found the same issue.

I discovered this last month and figured it was not a big deal, but a large part of our user base consists of non-technical elected officials and staff that would open the app in a default browser (IE). Can you look into why the widget does not show projects when they are selected? This is a higher priority than other widget development.

**Comment by stdavis** [comment]
I'll see if I can get to this today or tomorrow.

**Comment by stdavis** [comment]
I just want to let you know that I haven't forgotten about this. We haven't consciously supported IE for a while and I'm working to get the toolset for this project working for it.

**Comment by stdavis** [comment]
@msilski I've got the IE support figured out.

Checkout the new release for the ProjectInfo widget here: https://github.com/agrc/wfrc-wab-widgets/releases/tag/v1.1.1

Also, you'll need to follow the newly added steps for adding a polyfill to your app here: https://github.com/agrc/wfrc-wab-widgets/releases/tag/v1.1.1

Let me know if you have any questions.

**Comment by msilski** [comment]
Hi Scott - I noticed in the test [app](http://test.mapserv.utah.gov/wfrctests) that the Project Information widget does not select projects in Internet Explorer. I am testing the newest release of the Project Information widget and noticed the same thing. Can you take a look at it? Thanks.

**Comment by msilski** [comment]
It was the polyfill. I am using the Project Information widget in another web [app](**url**). Crisis averted ...

**Comment by stdavis** [comment]
Yes, the polyfill is key for IE support.
