### ISSUE TITLE
URL Params: Selected Project does not work after panning the map

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#27]
#### Repro
1. Click on a project
1. Pan the map
1. Copy the URL and paste into a new window.

#### Expected behavior
The app should open zoomed to the location with the project selected.

#### Actual behavior
The map zooms to the correct location but the project is not selected.

**Comment by stdavis** [comment]
@msilski I'm having troubles reproducing this one in my development app and I don't see the URL Params widget working in your production app: https://wfrc.org/rtp-2019-phasing/. Is there another app that I can reproduce this bug in?

**Comment by msilski** [comment]
Yes. Our new production app is [(https://wfrc.org/rtp-2019-adopted)]. It is implemented in this one.

**Comment by stdavis** [comment]
I'm not able to find a layer in that map that has a global id field which is required for the URL params widget to remember the selected feature. I can see the bug in my code and I can fix it but I don't have any data to test it with. Would you like me to fix it and pass it on to you to test?

**Comment by msilski** [comment]
That makes sense - since the layers in our rtp-2019-adopted map did not need commenting, I must not have added Global IDs. I'll add them to our layers and let you know when that's complete.

**Comment by msilski** [comment]
I added Global IDs to our layers. For line and polygon features, the URL takes you to the project and zooms in, which is great. For point features, it does not look like it is zooming in to the extent, but perhaps this is the expected behavior. We can review tomorrow morning.

**Comment by msilski** [comment]
For point features, let's go with a scale of 1:4,514. I think that zoom level gives enough background context.

**Comment by stdavis** [comment]
Give the [newest release](https://github.com/agrc/wfrc-wab-widgets/releases/tag/v1.6.1) a try and let me know what you think. Please note that I added a `pointZoomLevel` to the URLParams widget config file. You'll want to update your corresponding config file in your app. Level `17` is `1:4514`.

**Comment by msilski** [comment]
Sounds good. I will try it out and let you know when it's live.

**Comment by msilski** [comment]
This works and is now live. Thanks for the quick fix.
