### ISSUE TITLE
Unchecking Phasing checkboxes does not clear project layers

### ISSUE THREAD

**Issue by msilski** [agrc/wfrc-wab-widgets#28]
When all Phasing checkboxes are unchecked, the map does not recognize the action (see RTP [map](https://wfrc.org/rtp-2019-adopted)). For example, unchecking the "Phasing (colors)" group checkbox changes the URL to /#modes=roads&modes=transit&modes=bikeped but does not clear the roads, transit, and bike/ped layers from the map. The same error occurs when only one phase is checked and is then unchecked.

**Comment by msilski** [comment]
I see that this works in the test [app](http://test2.mapserv.utah.gov/WFRCTests). So this may be a configuration issue on my end. I will investigate further, but you are welcome to investigate as well.

It is worth noting that I have somewhat customized the Filter widget for use in this RTP [map](https://wfrc.org/rtp-2019-adopted). I removed the Utah County layers, edited the line symbols, changed the colors of the patches, removed a few of the "Other" datasets, and added "Existing Transit" under "Other." However, I noticed the phasing checkbox error before I made these changes.

**Comment by stdavis** [comment]
I wasn't able to reproduce this error in development but I definitely could see it in your production app. I stepped through the code in production and _think_ that I've found the bug and fixed it in v1.6.1 (Filter widget). Give it a try and let me know.

**Comment by msilski** [comment]
Thanks for looking into this. I'll give it a try using the new release.

**Comment by msilski** [comment]
Excellent! This works great and is in production. That's the last thing I can think of that would need to be fixed on our RTP [map](https://wfrc.org/rtp-2019-adopted).
