### ISSUE TITLE
Feedback for v0.1.0

### ISSUE THREAD

**Issue by bertgranberg** [agrc/wfrc-wab-widgets#5]
We successfully deployed the build to our server. Yay!

We showed the functionality to a small group here. People are generally pleased.

### Questions

About Widget

- [x] Can we use 'left dots' (similar to story map journal) within the About widget to jump to anchor tags...or is it possible to use html anchor tags (together with a short table of contents section that we write in html, not-hard coded) to jump to sections within the About pane 

Project Info Widget

- [x] We'd like to control the order of the features displayed in the widget info pane with projects drawing first by type, then centers. We are of course open to controlling draw order with a feature attribute (rather than hard coding this).
- [x] Is it possible for the project info widget, in cases where it 'hits' more than one feature, to only highlight features on the map upon their expansion in the widget info pane. To clarify, if one item is hit, it should be expanded by default and highlighted. If two or more items are hit, it should be possible to expand more than one at a time on the info pane, and as items are expanded or contracted they are highlighted (or dehighlighted) from the map.

**Comment by msilski** [comment]
Here is the temporary URL for the app on our server: http://wfrc.org/rtp-2019-phasing/

**Comment by stdavis** [comment]
> * Can we use 'left dots'...

I think that we can come up with something. I've created a separate issue for this request: https://github.com/agrc/wfrc-wab-widgets/issues/8

> We'd like to control the order...

For feature ordering. Do you want subheadings? Or maybe just a separation in the list to show that the features are from types/layers?

> * s it possible for the project info widget, in cases where it 'hits' more than one feature...

I'll get to work on this.

**Comment by stdavis** [comment]
I'm closing this in favor of #21
