### ISSUE TITLE
BetterAbout: Table of Contents

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#8]
From @bertgranberg:
>Can we use 'left dots' (similar to story map journal) within the About widget to jump to anchor tags...or is it possible to use html anchor tags (together with a short table of contents section that we write in html, not-hard coded) to jump to sections within the About pane

e.g. https://wfrc.maps.arcgis.com/apps/MapJournal/index.html?appid=dc844cc6022e40edb2813b6a73339844

**Comment by msilski** [comment]
I guess I can't just attach a JSON file ... so here is the config.json file found in the root directory of the web application, pasted into a text file:

[config_json.txt](https://github.com/agrc/wfrc-wab-widgets/files/2417298/config_json.txt)

Screenshot of config.json file location:

![config json location](https://user-images.githubusercontent.com/1699870/46046785-95e73e00-c0df-11e8-945b-214a541690b4.JPG)

The HTML under the About widget section is what is being referenced in the left side panel. It was originally copied from a story map, so it has extra spans and things that I meant to clean up, but haven't yet.

**Comment by stdavis** [comment]
I was able to make a simple table of contents work by using anchor tags and header ids within the HTML of the BetterAbout widget without any changes to the widget code.

Here's an example of how it would be done with your HTML: 
[temp.txt](https://github.com/agrc/wfrc-wab-widgets/files/2428330/temp.txt)

I've added documentation on how to do this to the [README for this project](https://github.com/agrc/wfrc-wab-widgets).

Please note that I removed the styling around the header and anchor tags just to make the code more clear. You will likely want to re-style them.

Also, I also took the liberty of removing the anchor tags that were wrapping your images. This was causing issues with the image popups (which are build automatically for every image tag by the BetterAbout widget).
